// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAon9YRSztiPBr2Sz1jUGqhir-N0Mqpk98',
    appId: '1:654531668513:web:b133b00428d73d57ecd160',
    messagingSenderId: '654531668513',
    projectId: 'eco-mall-system-d57ae',
    authDomain: 'eco-mall-system-d57ae.firebaseapp.com',
    storageBucket: 'eco-mall-system-d57ae.appspot.com',
    measurementId: 'G-23RP1CKX7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlSIp4fN4vZcz9-zplr0_TLYstHrp4cA',
    appId: '1:654531668513:android:20123274e00b9360ecd160',
    messagingSenderId: '654531668513',
    projectId: 'eco-mall-system-d57ae',
    storageBucket: 'eco-mall-system-d57ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiiz-kgos09aVPEQoZM978iYsEQjase8',
    appId: '1:654531668513:ios:84df67aa724a6dc1ecd160',
    messagingSenderId: '654531668513',
    projectId: 'eco-mall-system-d57ae',
    storageBucket: 'eco-mall-system-d57ae.appspot.com',
    iosBundleId: 'com.example.ecoMallSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdiiz-kgos09aVPEQoZM978iYsEQjase8',
    appId: '1:654531668513:ios:84df67aa724a6dc1ecd160',
    messagingSenderId: '654531668513',
    projectId: 'eco-mall-system-d57ae',
    storageBucket: 'eco-mall-system-d57ae.appspot.com',
    iosBundleId: 'com.example.ecoMallSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAon9YRSztiPBr2Sz1jUGqhir-N0Mqpk98',
    appId: '1:654531668513:web:d9ae4196ff0294baecd160',
    messagingSenderId: '654531668513',
    projectId: 'eco-mall-system-d57ae',
    authDomain: 'eco-mall-system-d57ae.firebaseapp.com',
    storageBucket: 'eco-mall-system-d57ae.appspot.com',
    measurementId: 'G-C18QREKVTS',
  );
}
